import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <main>Loading...</main>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-3xl">Guestbook</h1>
        <p className="mt-2 mb-6">
          Tutorial for <code>create-t3-app</code>
        </p>
        {session ? (
          <div>
            <p> Hi {session.user?.name}</p>
            <button
              className="group relative inline-block text-sm font-medium text-white focus:outline-none focus:ring"
              onClick={() => signOut()}
            >
              <span className="absolute inset-0 border border-red-600 group-active:border-red-500"></span>
              <span className="block border border-red-600 bg-red-600 px-12 py-3 transition-transform active:border-red-500 active:bg-red-500 group-hover:-translate-x-1 group-hover:-translate-y-1">
                Logout
              </span>
            </button>
            <div className="pt-10">
              <Messages />
            </div>
          </div>
        ) : (
          <div>
            <button
              className="group relative inline-block text-sm font-medium text-white focus:outline-none focus:ring"
              onClick={() => signIn("discord")}
            >
              <span className="absolute inset-0 border border-red-600 group-active:border-red-500"></span>
              <span className="block border border-red-600 bg-red-600 px-12 py-3 transition-transform active:border-red-500 active:bg-red-500 group-hover:-translate-x-1 group-hover:-translate-y-1">
                Login
              </span>
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;

const Messages = () => {
  const { data: messages, isLoading } = trpc.useQuery(["guestbook.getAll"]);

  if (isLoading) return <div>Fetching messages...</div>;

  return (
    <div className="flex flex-col gap-4">
      {messages?.map((msg, index) => {
        return (
          <div key={index}>
            <p>{msg.message}</p>
            <span>- {msg.name}</span>
          </div>
        );
      })}
    </div>
  );
};
